version: '3.12.7'
services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata:
    driver: local
